### ISSUE TITLE
Change access modifiers of autoregistration attributes

### ISSUE THREAD

**Issue by NiceOneFox** [patrickklaeren/AutoRegisterInject#16]
Hi, you should change access modifiers of attributes for autogenerating source code(RegisterSingleton etc) to internal as if one project reference another(both have sourcegen) you get generating attributes for each project and it rise a compile warning as it don't know exactly know which attribute to use.
If you wonder why I have two projects referencing sourcegen, it's because I register services of another project.

**Comment by patrickklaeren** [comment]
I'm not sure I follow.

The attributes are already internal, and sealed.

https://github.com/patrickklaeren/AutoRegisterInject/blob/38baabcf4f63c4b7c2e4c0f94a0de506e6add166/src/AutoRegisterInject/SourceConstants.cs#L10

**Comment by NiceOneFox** [comment]
Oh, that's nice.
I used fork so didn't notice.
Thanks
