### ISSUE TITLE
Can't register service multiple times in multiple ways.

### ISSUE THREAD

**Issue by ristogod** [patrickklaeren/AutoRegisterInject#17]
We tried this and only the first register works. the two subsequent registries do not appear in the AutoRegister generated code.

``` csharp
[RegisterTransient(typeof(IHarvestService))]
[TryRegisterTransient(typeof(IAccountService))]
[TryRegisterKeyedTransient(Key, typeof(IHarvestService))]
public partial class AccountService : IAccountService
```

**Comment by patrickklaeren** [comment]
This is intentional as per my opinion:

https://github.com/patrickklaeren/AutoRegisterInject/wiki/Edgecases#multiple-lifetime-registration

**Comment by ristogod** [comment]
Odd opinion to intentionally deviate from a very common usage scenario. As is, when using AutoRegister, services' registries will be split between annotations and code. Very much defeating the purpose of this package.
