### ISSUE TITLE
Support keyed services

### ISSUE THREAD

**Issue by patrickklaeren** [patrickklaeren/AutoRegisterInject#5]
New attributes to register as keyed services, string to indicate their key.

**Comment by ristogod** [comment]
Just curious if this is a planned feature add and if so whether or not you could speculate on a timeline. Thanks.

**Comment by patrickklaeren** [comment]
At this time, I do not have a commitment to give. Likely to be in the next couple of months, nearing the start of summer.

**Comment by patrickklaeren** [comment]
Available in https://github.com/patrickklaeren/AutoRegisterInject/releases/tag/v1.4.0
