### ISSUE TITLE
Support TryAdd methods

### ISSUE THREAD

**Issue by ristogod** [patrickklaeren/AutoRegisterInject#6]
Instead of using methods such as AddTransient and AddSingleton, can it use TryAddTransient and TryAddSingleton (including the other possible lifetimes)? Or possibly make it configurable?

**Comment by patrickklaeren** [comment]
I imagine covering everyone's requirements can be quite difficult here.

I suggest to implement new attributes, `TryRegisterScoped`, and co.

My concern here is ultimately for the ordering of what happens vs expectation.

**Comment by patrickklaeren** [comment]
Available in https://github.com/patrickklaeren/AutoRegisterInject/releases/tag/v1.4.0
